version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  solver-server-1:
    build:
      context: ./backend
    container_name: solver-server-1
    env_file:
      - ./backend/.env 
    environment:
      PORT: 4444
    depends_on:
      - db

  solver-server-2:
    build:
      context: ./backend
    container_name: solver-server-2
    env_file:
      - ./backend/.env 
    environment:
      PORT: 4444
    depends_on:
      - db

  nginx-load-balancer:
    image: nginx:stable-alpine
    container_name: nginx_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - solver-server-1
      - solver-server-2

volumes:
  mongo_data:
